/*
 * src/Saphir/Generator/SceneRendering.cpp
 * This file is part of Emeraude-Engine
 *
 * Copyright (C) 2010-2026 - Sébastien Léon Claude Christian Bémelmans "LondNoir" <londnoir@gmail.com>
 *
 * Emeraude-Engine is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Emeraude-Engine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Emeraude-Engine; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Complete project and additional information can be found at :
 * https://github.com/EmeraudeEngine/emeraude-engine
 *
 * --- THIS IS AUTOMATICALLY GENERATED, DO NOT CHANGE ---
 */

#include "SceneRendering.hpp"

/* Local inclusions. */
#include "Graphics/BindlessTextureManager.hpp"
#include "Graphics/Material/Interface.hpp"
#include "Graphics/RenderTarget/Abstract.hpp"
#include "Graphics/Renderer.hpp"
#include "Hash/FNV1a.hpp"
#include "Saphir/Code.hpp"
#include "Scenes/Scene.hpp"
#include "SkinningLayoutHelper.hpp"
#include "Vulkan/Framebuffer.hpp"
#include "Vulkan/RenderPass.hpp"

namespace EmEn::Saphir::Generator
{
	using namespace Base;
	using namespace Graphics;
	using namespace Vulkan;
	using namespace Saphir::Keys;

	void
	SceneRendering::prepareUniformSets (SetIndexes & setIndexes) noexcept
	{
		setIndexes.enableSet(SetType::PerView);

		/* Scene instance transforms SSBO (non-instanced model matrices, classic AND
		 * advanced). This decision seals the pipeline layout; the CPU binding follows
		 * setIndexes (pipeline layout) while the matrix source follows
		 * Program::wasInstanceTransformsEnabled() (shader code) — keep both conditions
		 * separate (see src/Saphir/AGENTS.md § "InstanceTransforms SSBO Path"). */
		if ( this->useInstanceTransformsSet() )
		{
			setIndexes.enableSet(SetType::PerSceneTransforms);
		}

		if ( this->isFlagEnabled(IsLightingEnabled) )
		{
			switch ( m_renderPassType )
			{
				case RenderPassType::DirectionalLightPass :
				case RenderPassType::DirectionalLightPassShadowMap :
				case RenderPassType::DirectionalLightPassCSM :
				case RenderPassType::DirectionalLightPassColorMap :
				case RenderPassType::DirectionalLightPassFull :
				case RenderPassType::DirectionalLightPassFullCSM :
				case RenderPassType::PointLightPass :
				case RenderPassType::PointLightPassShadowMap :
				case RenderPassType::PointLightPassColorMap :
				case RenderPassType::PointLightPassFull :
				case RenderPassType::SpotLightPass :
				case RenderPassType::SpotLightPassShadowMap :
				case RenderPassType::SpotLightPassColorMap :
				case RenderPassType::SpotLightPassFull :
					setIndexes.enableSet(SetType::PerLight);
					break;

				default:
					break;
			}
		}

		if ( this->isSkeletalAnimationEnabled() )
		{
			setIndexes.enableSet(SetType::PerModel);
		}

		if ( this->materialEnabled() )
		{
			setIndexes.enableSet(SetType::PerModelLayer);
		}

		/* Enable the bindless texture set when bindless textures are in use. */
		if ( this->bindlessTexturesEnabled() )
		{
			setIndexes.enableSet(SetType::PerBindless);
		}
	}

	bool
	SceneRendering::onGenerateShadersCode (Program & program) noexcept
	{
		/* Configure the light generator with the material for all shaders. */
		if ( this->isLightingRequested() )
		{
			if ( m_scene == nullptr )
			{
				Tracer::error(ClassId, "There is not scene to query light information from !");

				return false;
			}

			if ( this->materialEnabled() )
			{
				if ( !this->getMaterialInterface()->setupLightGenerator(m_lightGenerator) )
				{
					TraceError{ClassId} << "Unable to configure the light generator with material '" << this->getMaterialInterface()->name() << "' !";

					return false;
				}
			}
		}

		/* Generate the vertex shader stage. */
		if ( !this->generateVertexShader(program) )
		{
			/* NOTE: Error message is generated by the function. */
			return false;
		}

		if ( this->debuggingEnabled() )
		{
			program.vertexShader()->traceSuccessfulGeneration();
		}

		/* Generate the fragment shader stage. */
		if ( !this->generateFragmentShader(program) )
		{
			/* NOTE: Error message is generated by the function. */
			return false;
		}

		if ( this->debuggingEnabled() )
		{
			program.fragmentShader()->traceSuccessfulGeneration();;
		}

		return true;
	}

	bool
	SceneRendering::useInstanceTransformsSet () const noexcept
	{
		if ( this->isMultiDrawIndirectEnabled() )
		{
			return false;
		}

		if ( this->renderTarget()->isCubemap() )
		{
			return false;
		}

		/* NOTE: Instanced programs carry their model matrices in a VBO — they only need
		 * the set for the {viewProjection, previousViewProjection} HEADER, read by the
		 * velocity pass. Without a velocity attachment, no set. */
		if ( this->isFlagEnabled(IsInstancingEnabled) && !m_hasVelocityAttachment )
		{
			return false;
		}

		return m_scene != nullptr && m_scene->instanceTransforms().isInitialized();
	}

	bool
	SceneRendering::isLightingRequested () const noexcept
	{
		if ( m_scene == nullptr || !m_scene->lightSet().isEnabled() )
		{
			return false;
		}

		if ( !this->isFlagEnabled(IsLightingEnabled) )
		{
			return false;
		}

		/* The material-level veto: a material declaring itself UNLIT is never lit, whatever the
		 * instance asked for. Re-lighting content that already carries its own radiance
		 * double-counts it — the exact defect the unlit path exists to prevent. */
		if ( this->materialEnabled() && this->getMaterialInterface()->isUnlit() )
		{
			return false;
		}

		return true;
	}

	bool
	SceneRendering::isAdvancedRendering () const noexcept
	{
		if ( this->getMaterialInterface()->isComplex() )
		{
			return true;
		}

		switch ( m_renderPassType )
		{
			case RenderPassType::SimplePass :
				return false;

			case RenderPassType::DirectionalLightPass :
			case RenderPassType::DirectionalLightPassShadowMap :
			case RenderPassType::DirectionalLightPassCSM :
			case RenderPassType::DirectionalLightPassColorMap :
			case RenderPassType::DirectionalLightPassFull :
			case RenderPassType::DirectionalLightPassFullCSM :
			case RenderPassType::PointLightPass :
			case RenderPassType::PointLightPassShadowMap :
			case RenderPassType::PointLightPassColorMap :
			case RenderPassType::PointLightPassFull :
			case RenderPassType::SpotLightPass :
			case RenderPassType::SpotLightPassShadowMap :
			case RenderPassType::SpotLightPassColorMap :
			case RenderPassType::SpotLightPassFull :
				return true;

			case RenderPassType::AmbientPass :
				/* Advanced matrices are needed when:
				 * 1. MRT normal output requires view-space normals (normals attachment), OR
				 * 2. Normal mapping is active (light generator produces TBN code needing V*M).
				 * Both cases require separate V and M matrices to compute the normal matrix. */
				if ( this->isLightingRequested() )
				{
					return m_hasNormalsAttachment || m_lightGenerator.usesNormalMapping();
				}

				return false;

			default:
				return false;
		}
	}

	bool
	SceneRendering::onCreateDataLayouts (Renderer & renderer, const SetIndexes & setIndexes, StaticVector< std::shared_ptr< DescriptorSetLayout >, 6 > & descriptorSetLayouts, StaticVector< VkPushConstantRange, 4 > & pushConstantRanges) noexcept
	{
		/* Prepare the descriptor set layout for the scene instance transforms SSBO.
		 * NOTE: Must come right after the PerView layout (set index order). */
		if ( setIndexes.isSetEnabled(SetType::PerSceneTransforms) )
		{
			auto descriptorSetLayout = Scenes::SceneInstanceTransforms::getDescriptorSetLayout(renderer.layoutManager());

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the instance transforms descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		if ( m_scene != nullptr && setIndexes.isSetEnabled(SetType::PerLight) )
		{
			/* NOTE: Use the unified layout (2 bindings: UBO + shadow sampler).
			 * Shadow behavior is controlled by the scUseShadow specialization constant.
			 * The Vulkan driver eliminates dead code when scUseShadow is false. */
			auto descriptorSetLayout = Scenes::LightSet::getDescriptorSetLayout(renderer.layoutManager());

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the light descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		/* Prepare the descriptor set layout for skeletal animation bone matrices. */
		if ( setIndexes.isSetEnabled(SetType::PerModel) )
		{
			auto descriptorSetLayout = getSkinningDescriptorSetLayout(renderer.layoutManager());

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the skinning SSBO descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		/* Prepare the descriptor set layout for the model layer. */
		if ( this->materialEnabled() && setIndexes.isSetEnabled(SetType::PerModelLayer) )
		{
			auto descriptorSetLayout = this->getMaterialInterface()->descriptorSetLayout();

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the material descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		/* Prepare the descriptor set layout for bindless textures. */
		if ( setIndexes.isSetEnabled(SetType::PerBindless) )
		{
			auto descriptorSetLayout = renderer.bindlessTextureManager().descriptorSetLayout();

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the bindless textures descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		Abstract::generatePushConstantRanges(this->shaderProgram()->vertexShader()->pushConstantBlockDeclarations(), pushConstantRanges, VK_SHADER_STAGE_VERTEX_BIT);

		return true;
	}

	bool
	SceneRendering::generateVertexShader (Program & program) noexcept
	{
		/* Create the vertex shader. */
		const bool isCubemapTarget = this->renderTarget()->isCubemap();

		auto * vertexShader = program.initVertexShader(
			this->name( ) + "VertexShader",
			this->isFlagEnabled(IsInstancingEnabled),
			this->isAdvancedRendering(),
			this->isFlagEnabled(IsRenderableFacingCamera),
			isCubemapTarget,
			this->isMultiDrawIndirectEnabled()
		);
		vertexShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		/* Instanced motion history: fixes the per-instance VBO stride (previous model matrix). */
		if ( this->isInstanceMotionHistoryEnabled() )
		{
			vertexShader->enableInstanceMotionHistory();
		}

		/* Infinity view (sky background): selects the previous INFINITY view-projection for the
		 * velocity outputs. Part of the generator flags, hence of the program cache key — two
		 * instances of the same renderable, one infinity-view and one not, MUST NOT share a
		 * program. */
		if ( this->isUsingInfinityView() )
		{
			vertexShader->enableInfinityView();
		}

		/* NOTE: Cubemap rendering requires multiview extension for gl_ViewIndex. */
		if ( isCubemapTarget )
		{
			vertexShader->setExtensionBehavior("GL_EXT_multiview", "enable");
		}

		/* Scene instance transforms SSBO: the model matrix source of the non-instanced
		 * path (classic AND advanced), and the {VP, previousVP} header source of the
		 * velocity pass (instanced programs included). The matrix-source flag MUST be set
		 * before declareMatrixPushConstantBlock() (it selects the VP/V-only push block)
		 * and NEVER applies to instanced programs (their matrices live in a VBO). */
		if ( program.setIndexes().isSetEnabled(SetType::PerSceneTransforms) )
		{
			if ( !this->isFlagEnabled(IsInstancingEnabled) )
			{
				vertexShader->enableInstanceTransforms();
			}

			const auto setIndex = program.setIndexes().set(SetType::PerSceneTransforms);

			/* NOTE: {model, previousModel} interleaved (stride 2), preceded by the
			 * {previousViewProjection, previousViewProjectionInfinity} header reserved for the
			 * motion-vector pass — the second one serves the renderables rendered with the
			 * translation-free INFINITY view (the sky), whose velocity would otherwise be wrong
			 * by the camera translation. Both header matrices are UNJITTERED — the TAA sub-pixel
			 * jitter is a per-draw push constant applied to gl_Position only, so the velocity clip
			 * positions computed from this header need no jitter correction.
			 * Must match Scenes::SceneInstanceTransforms GPU layout. */
			Declaration::ShaderStorageBlock ssbo{setIndex, 0, Declaration::MemoryLayout::Std430, "InstanceTransforms", "ubInstanceTransforms"};
			ssbo.setAccessQualifier(Declaration::AccessQualifier::ReadOnly);
			ssbo.addMember(Declaration::VariableType::Matrix4, "previousViewProjection");
			ssbo.addMember(Declaration::VariableType::Matrix4, "previousViewProjectionInfinity");
			ssbo.addMember(Declaration::VariableType::Matrix4, "instanceMatrices[]");
			vertexShader->declare(ssbo);
		}

		if ( !this->declareMatrixPushConstantBlock(*vertexShader) )
		{
			return false;
		}

		/* Declare the view uniform block. */
		if ( !this->declareViewUniformBlock(*vertexShader) )
		{
			return false;
		}

		/* Skeletal animation: declare bone attributes and SSBO. */
		if ( this->isSkeletalAnimationEnabled() )
		{
			vertexShader->enableSkinning();

			vertexShader->declare(Declaration::InputAttribute{Graphics::VertexAttributeType::BoneInfluence});
			vertexShader->declare(Declaration::InputAttribute{Graphics::VertexAttributeType::BoneWeight});

			const auto setIndex = program.setIndexes().set(SetType::PerModel);

			Declaration::ShaderStorageBlock ssbo{setIndex, 0, Declaration::MemoryLayout::Std430, "SkinningMatrices", "ubSkinningMatrices"};
			ssbo.setAccessQualifier(Declaration::AccessQualifier::ReadOnly);
			ssbo.addMember(Declaration::VariableType::Matrix4, "bones[]");
			vertexShader->declare(ssbo);
		}

		/* NOTE: The position is always required and available. */
		if ( !vertexShader->requestSynthesizeInstruction(ShaderVariable::PositionScreenSpace) )
		{
			return false;
		}

		/* Velocity outputs (motion vectors): current and previous clip-space positions,
		 * turned into an NDC delta by the fragment shader. Requires the InstanceTransforms
		 * SSBO header (previousViewProjection). */
		m_velocityOutputsEmitted = false;

		if ( m_hasVelocityAttachment && program.setIndexes().isSetEnabled(SetType::PerSceneTransforms) )
		{
			if ( !vertexShader->synthesizeVelocityClipPositions(*this, m_velocityOutputsEmitted) )
			{
				return false;
			}
		}

		/* If present, generate the material shader code. */
		if ( this->materialEnabled() && !this->getMaterialInterface()->generateVertexShaderCode(*this, *vertexShader) )
		{
			TraceError{ClassId} << "Unable to generate vertex shader code part for material '" << this->getMaterialInterface()->name() << "' !";

			return false;
		}

		/* Generate the lighting shader code. */
		if ( this->isLightingRequested() )
		{
			if ( !m_lightGenerator.generateVertexShaderCode(*this, *vertexShader) )
			{
				Tracer::error(ClassId, "Unable to generate vertex shader code part for lighting !");

				return false;
			}

			/* Ensure svNormalViewSpace is available as a fragment shader input for the MRT normal output.
			 * Only needed when the render target has a normals attachment (color attachment count >= 2),
			 * i.e. the internal scene render target.  The swap chain has only 1 color attachment. */
			if ( m_hasNormalsAttachment )
			{
				if ( !vertexShader->requestSynthesizeInstruction(ShaderVariable::NormalViewSpace, Saphir::VariableScope::ToNextStage) )
				{
					return false;
				}
			}
		}

		return vertexShader->generateSourceCode(*this);
	}

	bool
	SceneRendering::generateFragmentShader (Program & program) noexcept
	{
		/* Create the fragment shader. */
		auto * fragmentShader = program.initFragmentShader(this->name( ) + "FragmentShader");
		fragmentShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		/* Automatic input declarations from vertex shader. */
		if ( !fragmentShader->connectFromPreviousShader(*program.vertexShader()) )
		{
			return false;
		}

		/* Common part of fragment shader. */
		fragmentShader->declareDefaultOutputFragment();

		/* Declare the MRT normals output only when the render target has a normals attachment. */
		if ( m_hasNormalsAttachment )
		{
			fragmentShader->declare(Declaration::OutputFragment{1, Keys::GLSL::FloatVector4, Keys::ShaderVariable::OutputNormal});
		}

		/* Declare the MRT material properties output only when the render target has the attachment. */
		if ( m_hasMaterialPropertiesAttachment )
		{
			fragmentShader->declare(Declaration::OutputFragment{2, Keys::GLSL::FloatVector4, Keys::ShaderVariable::OutputMaterialProperties});
		}

		/* Declare the MRT albedo output only when the render target has the attachment. */
		if ( m_hasAlbedoAttachment )
		{
			fragmentShader->declare(Declaration::OutputFragment{3, Keys::GLSL::FloatVector4, Keys::ShaderVariable::OutputAlbedo});
		}

		/* Declare the MRT velocity output only when the render target has the attachment. */
		if ( m_hasVelocityAttachment )
		{
			fragmentShader->declare(Declaration::OutputFragment{4, Keys::GLSL::FloatVector2, Keys::ShaderVariable::OutputVelocity});
		}

		/* If a material is present, generate the shader code (optional). */
		if ( this->materialEnabled() && !this->getMaterialInterface()->generateFragmentShaderCode(*this, m_lightGenerator, *fragmentShader) )
		{
			TraceError{ClassId} << "Unable to generate fragment shader code part for material '" << this->getMaterialInterface()->name() << "' !";

			return false;
		}

		/* NOTE: Queried twice below (light generation, then fragment output); the
		 * underlying check chases scene/material state through several virtual calls,
		 * and neither call site can change what it would return, so compute it once. */
		const bool lightingRequested = this->isLightingRequested();

		/* If the light is enabled, generate the shader code (optional). */
		if ( lightingRequested )
		{
			/* Declare the view uniform block. */
			if ( !this->declareViewUniformBlock(*fragmentShader) )
			{
				return false;
			}

			if ( !m_lightGenerator.generateFragmentShaderCode(*this, *fragmentShader) )
			{
				Tracer::error(ClassId, "Unable to generate fragment shader code part for lighting !");

				return false;
			}
		}

		/* Generates the fragment output. */
		if ( lightingRequested )
		{
			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = " << m_lightGenerator.fragmentColor() << ';';

			if ( m_hasNormalsAttachment )
			{
				/* Write view-space normal to MRT attachment 1 for post-process effects (SSAO, SSR, RTR, RTAO).
				 * Uses the final normal (perturbed by normal mapping when active) instead of the geometric normal.
				 * Alpha packs roughness + metalness: alpha = roughness + round(metalness) * 2.0.
				 * Decode: metalness = (alpha >= 2.0) ? 1.0 : 0.0; roughness = alpha - metalness * 2.0;
				 * ⚠️ The metalness MUST be quantized to {0,1} at WRITE time: the decode's >= 2
				 * threshold assumes it. A fractional metalness (real since the packed
				 * metallic-roughness source channels are honored) would otherwise corrupt BOTH
				 * decoded values — 0.93 metal / 0.4 rough packed raw decodes as 1.0 / 0.26.
				 * Only the ambient/simple pass writes the actual normal. Light passes use additive
				 * blending, so they must output zero to preserve the existing normal value. */
				if ( m_renderPassType == RenderPassType::AmbientPass || m_renderPassType == RenderPassType::SimplePass )
				{
					const auto normalExpr = m_lightGenerator.finalNormalViewSpaceExpression();
					const auto roughnessExpr = m_lightGenerator.roughnessShaderExpression();
					const auto metalnessExpr = m_lightGenerator.metalnessShaderExpression();
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(" << normalExpr << ", clamp(" << roughnessExpr << ", 0.0, 1.0) + round(clamp(" << metalnessExpr << ", 0.0, 1.0)) * 2.0);";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(0.0);";
				}
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				/* Write material properties to MRT attachment 2 for post-process effect modulation.
				 * Nibble-packed RGBA: R[hi:lo]=reflection:reserved, G[hi:lo]=aoResponse:shadowResponse,
				 * B[hi:lo]=bloomContrib:emissiveMask, A[hi:lo]=fogResponse:dofMask.
				 * Values derived from declared surface properties (metalness, roughness, AO, emissive).
				 *
				 * RGB is preserved across light passes via additive blend (write 0, add 0).
				 * Alpha uses REPLACE blend (srcAlpha=ONE, dstAlpha=ZERO) in light passes, so we
				 * MUST write A=1.0 to preserve the AmbientPass-encoded fogResponse/dofMask nibbles;
				 * writing vec4(0.0) here would zero out alpha and break AtmosphericFog/DepthOfField
				 * material modulation in every lit pixel. */
				if ( m_renderPassType == RenderPassType::AmbientPass || m_renderPassType == RenderPassType::SimplePass )
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = " << m_lightGenerator.materialPropertiesExpression() << ";";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = vec4(0.0, 0.0, 0.0, 1.0);";
				}
			}

			if ( m_hasAlbedoAttachment )
			{
				/* Write the surface DIFFUSE albedo to MRT attachment 3 for indirect-light
				 * modulation (SSGI, RTGI). ⚠️ NOT the base color: the attachment re-modulates a
				 * demodulated IRRADIANCE, so it carries the energy the diffuse lobe actually
				 * receives — see LightGenerator::diffuseAlbedoShaderExpression(). Only the
				 * ambient/simple pass writes it; light passes have their write mask zeroed on
				 * the G-buffer attachments (see onGraphicsPipelineConfiguration). */
				if ( m_renderPassType == RenderPassType::AmbientPass || m_renderPassType == RenderPassType::SimplePass )
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputAlbedo << " = vec4(" << m_lightGenerator.diffuseAlbedoShaderExpression() << ", 1.0);";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputAlbedo << " = vec4(0.0);";
				}
			}

			if ( m_hasVelocityAttachment )
			{
				/* Write the NDC-delta motion vector to MRT attachment 4 (temporal effects).
				 * NOTE: Jitter-free by construction — no matrix used to build the clip positions
				 * carries the TAA sub-pixel jitter (it is a per-draw push constant applied to
				 * gl_Position alone), so the plain NDC delta below needs no jitter terms.
				 * Light passes have their write mask zeroed (see onGraphicsPipelineConfiguration). */
				if ( m_velocityOutputsEmitted && (m_renderPassType == RenderPassType::AmbientPass || m_renderPassType == RenderPassType::SimplePass) )
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputVelocity << " = (" << ShaderVariable::ClipPositionCurrent << ".xy / " << ShaderVariable::ClipPositionCurrent << ".w) - (" << ShaderVariable::ClipPositionPrevious << ".xy / " << ShaderVariable::ClipPositionPrevious << ".w);";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputVelocity << " = vec2(0.0);";
				}
			}
		}
		else if ( this->materialEnabled() )
		{
			/* UNLIT path. With no lighting to add an emissive term over, a self-illuminating
			 * material's surface colour IS its emitted radiance, so the emission MULTIPLIES here
			 * (the lit path adds it instead — see LightGenerator). Without this, a skybox with a
			 * luminance of 8000 nits still rendered as its raw [0,1] cubemap, i.e. black once the
			 * scene went photometric: the simple pass wrote the surface colour verbatim. */
			const auto * material = this->getMaterialInterface();

			/* NOTE: fragmentColor() rebuilds its GLSL expression (component lookup + string
			 * concatenation) on every call; it is used up to four times below for the exact
			 * same material and layer, so compute it once. */
			const auto fragmentColorExpr = material->fragmentColor();

			if ( const auto emission = material->emissionMultiplier(); emission.empty() )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = " << fragmentColorExpr << ';';
			}
			else
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = vec4((" << fragmentColorExpr << ").rgb * " << emission << ", (" << fragmentColorExpr << ").a);";
			}

			if ( m_hasNormalsAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(0.0, 0.0, 1.0, 0.5);";
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = vec4(0.0, 1.0, 240.0 / 255.0, 1.0);";
			}

			if ( m_hasAlbedoAttachment )
			{
				/* Unlit material: its displayed color IS its albedo. */
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputAlbedo << " = vec4((" << fragmentColorExpr << ").rgb, 1.0);";
			}

			if ( m_hasVelocityAttachment )
			{
				if ( m_velocityOutputsEmitted )
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputVelocity << " = (" << ShaderVariable::ClipPositionCurrent << ".xy / " << ShaderVariable::ClipPositionCurrent << ".w) - (" << ShaderVariable::ClipPositionPrevious << ".xy / " << ShaderVariable::ClipPositionPrevious << ".w);";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputVelocity << " = vec2(0.0);";
				}
			}
		}
		else
		{
			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = vec4(1.0, 0.0, 1.0, 1.0);";

			if ( m_hasNormalsAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(0.0, 0.0, 1.0, 0.5);";
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = vec4(0.0, 1.0, 240.0 / 255.0, 1.0);";
			}

			if ( m_hasAlbedoAttachment )
			{
				/* No material: neutral white albedo (identity for indirect-light modulation). */
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputAlbedo << " = vec4(1.0);";
			}

			if ( m_hasVelocityAttachment )
			{
				if ( m_velocityOutputsEmitted )
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputVelocity << " = (" << ShaderVariable::ClipPositionCurrent << ".xy / " << ShaderVariable::ClipPositionCurrent << ".w) - (" << ShaderVariable::ClipPositionPrevious << ".xy / " << ShaderVariable::ClipPositionPrevious << ".w);";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputVelocity << " = vec2(0.0);";
				}
			}
		}

		/* Discard nearly transparent pixels to avoid blending artifacts. */
		if ( this->materialEnabled() && this->getMaterialInterface()->blendingMode() != BlendingMode::None )
		{
			Code{*fragmentShader, Location::Output} << "if ( " << ShaderVariable::OutputFragment << ".a < 0.01 ) discard;";
		}

		return fragmentShader->generateSourceCode(*this);
	}
	
	bool
	SceneRendering::onGraphicsPipelineConfiguration (const Program & /*program*/, GraphicsPipeline & graphicsPipeline) noexcept
	{
		const auto * renderableInstance = this->getRenderableInstance();
		const auto * renderable = renderableInstance->renderable();

		/* NOTE: Use dynamic viewport and scissor to avoid pipeline recreation on window resize. */
		{
			const StaticVector< VkDynamicState, 16 > dynamicStates{
				VK_DYNAMIC_STATE_VIEWPORT,
				VK_DYNAMIC_STATE_SCISSOR
			};

			if ( !graphicsPipeline.configureDynamicStates(dynamicStates) )
			{
				Tracer::error(ClassId, "Unable to configure the graphics pipeline dynamic states !");

				return false;
			}
		}

		/* A cubemap target renders through a mirrored projection — the front face must follow. */
		if ( !graphicsPipeline.configureRasterizationState(m_renderPassType, renderable->layerRasterizationOptions(this->layerIndex()), 0, this->renderTarget()->isCubemap()) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline rasterization state !");

			return false;
		}

		if ( !graphicsPipeline.configureDepthStencilState(m_renderPassType, *renderableInstance) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline depth/stencil state !");

			return false;
		}

		if ( !graphicsPipeline.configureColorBlendState(m_renderPassType, *renderable->material(this->layerIndex())) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline color blend state !");

			return false;
		}

		/* When the render target has MRT attachments (G-buffer: [1]=normals,
		 * [2]=material properties), the blend state differs per attachment
		 * (requires the 'independentBlend' device feature):
		 * - Ambient pass, opaque material: full write, same as the color attachment.
		 * - Ambient pass, translucent material: the color attachment keeps its alpha
		 *   blending, but the G-buffer receives the top-most surface data at 100%.
		 *   With the duplicated alpha blending, a translucent surface used to leave
		 *   only 'outNormal.a' (packed roughness+metalness, ~0.03 for water) of its
		 *   normal in the G-buffer — RTR/SSR then reflected off the surface BELOW
		 *   instead of the visible one (flat water reflections).
		 * - Light passes (additive): the G-buffer must never be modified — write
		 *   mask zero (previously they relied on shaders emitting vec4(0.0)). */
		if ( m_hasNormalsAttachment || m_hasMaterialPropertiesAttachment || m_hasAlbedoAttachment || m_hasVelocityAttachment )
		{
			auto gBufferState = graphicsPipeline.colorBlendAttachments()[0];

			if ( Graphics::renderPassIsLightPass(m_renderPassType) )
			{
				gBufferState.colorWriteMask = 0;
			}
			else if ( gBufferState.blendEnable == VK_TRUE )
			{
				gBufferState.blendEnable = VK_FALSE;
				gBufferState.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
				gBufferState.dstColorBlendFactor = VK_BLEND_FACTOR_ZERO;
				gBufferState.colorBlendOp = VK_BLEND_OP_ADD;
				gBufferState.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
				gBufferState.dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
				gBufferState.alphaBlendOp = VK_BLEND_OP_ADD;
			}

			if ( m_hasNormalsAttachment )
			{
				graphicsPipeline.appendColorBlendAttachment(gBufferState);
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				graphicsPipeline.appendColorBlendAttachment(gBufferState);
			}

			if ( m_hasAlbedoAttachment )
			{
				graphicsPipeline.appendColorBlendAttachment(gBufferState);
			}

			if ( m_hasVelocityAttachment )
			{
				graphicsPipeline.appendColorBlendAttachment(gBufferState);
			}
		}

		return true;
	}

	size_t
	SceneRendering::computeProgramCacheKey () const noexcept
	{
		/* NOTE: Helper function to combine hash values (boost::hash_combine style). */
		const auto hashCombine = [] (size_t & seed, size_t value) noexcept {
			seed ^= value + 0x9e3779b9 + (seed << 6) + (seed >> 2);
		};

		size_t hash = 0;

		/* 1. Render pass handle (critical for pipeline compatibility). */
		if ( const auto * framebuffer = this->renderTarget()->framebuffer(); framebuffer != nullptr )
		{
			hashCombine(hash, reinterpret_cast< size_t >(framebuffer->renderPass()->handle()));
		}

		/* 2. Render target type (cubemap vs single layer). */
		hashCombine(hash, static_cast< size_t >(this->renderTarget()->isCubemap()));

		/* 3. Renderable identity (geometry + material combination via resource name). */
		if ( this->isRenderableInstanceAvailable() )
		{
			const auto * renderable = this->getRenderable();

			if ( renderable != nullptr )
			{
				hashCombine(hash, Hash::FNV1a(renderable->name()));
			}
		}

		/* 4. Layer index. */
		hashCombine(hash, static_cast< size_t >(this->layerIndex()));

		/* 5. Render pass type. */
		hashCombine(hash, static_cast< size_t >(m_renderPassType));

		/* 6. Generator flags (instancing, lighting, facing camera, etc.). */
		hashCombine(hash, static_cast< size_t >(this->flags()));

		/* 7. Material layout signature to separate incompatible pipelines (e.g. Standard Refl/Refract). */
		if ( this->materialEnabled() )
		{
			if ( const auto & layout = this->getMaterialInterface()->descriptorSetLayout(); layout != nullptr )
			{
				hashCombine(hash, layout->getHash());
			}

			/* 8. Material codegen flag bits: two materials can share a descriptor layout yet
			 * generate structurally different GLSL (e.g. the alpha-test discard). */
			hashCombine(hash, static_cast< size_t >(this->getMaterialInterface()->flags()));
		}

		return hash;
	}
}
