/*
 * src/Saphir/Generator/SceneRendering.cpp
 * This file is part of Emeraude-Engine
 *
 * Copyright (C) 2010-2026 - Sébastien Léon Claude Christian Bémelmans "LondNoir" <londnoir@gmail.com>
 *
 * Emeraude-Engine is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Emeraude-Engine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Emeraude-Engine; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Complete project and additional information can be found at :
 * https://github.com/londnoir/emeraude-engine
 *
 * --- THIS IS AUTOMATICALLY GENERATED, DO NOT CHANGE ---
 */

#include "SceneRendering.hpp"

/* Local inclusions. */
#include "Graphics/BindlessTextureManager.hpp"
#include "Graphics/Renderer.hpp"
#include "Graphics/RenderTarget/Abstract.hpp"
#include "Graphics/Material/Interface.hpp"
#include "Libs/Hash/FNV1a.hpp"
#include "Vulkan/Framebuffer.hpp"
#include "Vulkan/RenderPass.hpp"
#include "Libs/SourceCodeParser.hpp"
#include "Scenes/Scene.hpp"
#include "Saphir/Code.hpp"

/* Local inclusions. */
#include "SkinningLayoutHelper.hpp"

namespace EmEn::Saphir::Generator
{
	using namespace Libs;
	using namespace Graphics;
	using namespace Vulkan;
	using namespace Saphir::Keys;

	void
	SceneRendering::prepareUniformSets (SetIndexes & setIndexes) noexcept
	{
		setIndexes.enableSet(SetType::PerView);

		if ( this->isFlagEnabled(IsLightingEnabled) )
		{
			switch ( m_renderPassType )
			{
				case RenderPassType::DirectionalLightPass :
				case RenderPassType::DirectionalLightPassShadowMap :
				case RenderPassType::DirectionalLightPassCSM :
				case RenderPassType::DirectionalLightPassColorMap :
				case RenderPassType::DirectionalLightPassFull :
				case RenderPassType::DirectionalLightPassFullCSM :
				case RenderPassType::PointLightPass :
				case RenderPassType::PointLightPassShadowMap :
				case RenderPassType::PointLightPassColorMap :
				case RenderPassType::PointLightPassFull :
				case RenderPassType::SpotLightPass :
				case RenderPassType::SpotLightPassShadowMap :
				case RenderPassType::SpotLightPassColorMap :
				case RenderPassType::SpotLightPassFull :
					setIndexes.enableSet(SetType::PerLight);
					break;

				default:
					break;
			}
		}

		if ( this->isSkeletalAnimationEnabled() )
		{
			setIndexes.enableSet(SetType::PerModel);
		}

		if ( this->materialEnabled() )
		{
			setIndexes.enableSet(SetType::PerModelLayer);
		}

		/* Enable the bindless texture set when bindless textures are in use. */
		if ( this->bindlessTexturesEnabled() )
		{
			setIndexes.enableSet(SetType::PerBindless);
		}
	}

	bool
	SceneRendering::onGenerateShadersCode (Program & program) noexcept
	{
		/* Configure the light generator with the material for all shaders. */
		if ( this->isFlagEnabled(IsLightingEnabled) )
		{
			if ( m_scene == nullptr )
			{
				Tracer::error(ClassId, "There is not scene to query light information from !");

				return false;
			}

			if ( m_renderPassType == RenderPassType::SimplePass && m_scene->lightSet().isUsingStaticLighting() )
			{
				/* FIXME: Check where to put the name of the static lighting! */
				const auto * staticLighting = m_scene->lightSet().getStaticLightingPointer();

				if ( staticLighting == nullptr )
				{
					TraceError{ClassId} << "The static lighting is not available from the scene !";

					return false;
				}

				m_lightGenerator.setStaticLighting(staticLighting);
			}

			if ( this->materialEnabled() )
			{
				if ( !this->getMaterialInterface()->setupLightGenerator(m_lightGenerator) )
				{
					TraceError{ClassId} << "Unable to configure the light generator with material '" << this->getMaterialInterface()->name() << "' !";

					return false;
				}
			}
		}

		/* Generate the vertex shader stage. */
		if ( !this->generateVertexShader(program) )
		{
			/* NOTE: Error message is generated by the function. */
			return false;
		}

		if ( this->debuggingEnabled() )
		{
			program.vertexShader()->traceSuccessfulGeneration();
		}

		/* Generate the fragment shader stage. */
		if ( !this->generateFragmentShader(program) )
		{
			/* NOTE: Error message is generated by the function. */
			return false;
		}

		if ( this->debuggingEnabled() )
		{
			program.fragmentShader()->traceSuccessfulGeneration();;
		}

		return true;
	}

	bool
	SceneRendering::isAdvancedRendering () const noexcept
	{
		if ( this->getMaterialInterface()->isComplex() )
		{
			return true;
		}

		switch ( m_renderPassType )
		{
			case RenderPassType::SimplePass :
				return m_scene->lightSet().isUsingStaticLighting();

			case RenderPassType::DirectionalLightPass :
			case RenderPassType::DirectionalLightPassShadowMap :
			case RenderPassType::DirectionalLightPassCSM :
			case RenderPassType::DirectionalLightPassColorMap :
			case RenderPassType::DirectionalLightPassFull :
			case RenderPassType::DirectionalLightPassFullCSM :
			case RenderPassType::PointLightPass :
			case RenderPassType::PointLightPassShadowMap :
			case RenderPassType::PointLightPassColorMap :
			case RenderPassType::PointLightPassFull :
			case RenderPassType::SpotLightPass :
			case RenderPassType::SpotLightPassShadowMap :
			case RenderPassType::SpotLightPassColorMap :
			case RenderPassType::SpotLightPassFull :
				return true;

			case RenderPassType::AmbientPass :
				/* Advanced matrices are needed when:
				 * 1. MRT normal output requires view-space normals (normals attachment), OR
				 * 2. Normal mapping is active (light generator produces TBN code needing V*M).
				 * Both cases require separate V and M matrices to compute the normal matrix. */
				if ( m_scene->lightSet().isEnabled() && this->isFlagEnabled(IsLightingEnabled) )
				{
					return m_hasNormalsAttachment || m_lightGenerator.usesNormalMapping();
				}

				return false;

			default:
				return false;
		}
	}

	bool
	SceneRendering::onCreateDataLayouts (Renderer & renderer, const SetIndexes & setIndexes, StaticVector< std::shared_ptr< DescriptorSetLayout >, 4 > & descriptorSetLayouts, StaticVector< VkPushConstantRange, 4 > & pushConstantRanges) noexcept
	{
		if ( m_scene != nullptr && setIndexes.isSetEnabled(SetType::PerLight) )
		{
			/* NOTE: Use the unified layout (2 bindings: UBO + shadow sampler).
			 * Shadow behavior is controlled by the scUseShadow specialization constant.
			 * The Vulkan driver eliminates dead code when scUseShadow is false. */
			auto descriptorSetLayout = Scenes::LightSet::getDescriptorSetLayout(renderer.layoutManager());

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the light descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		/* Prepare the descriptor set layout for skeletal animation bone matrices. */
		if ( setIndexes.isSetEnabled(SetType::PerModel) )
		{
			auto descriptorSetLayout = getSkinningDescriptorSetLayout(renderer.layoutManager());

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the skinning SSBO descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		/* Prepare the descriptor set layout for the model layer. */
		if ( this->materialEnabled() && setIndexes.isSetEnabled(SetType::PerModelLayer) )
		{
			auto descriptorSetLayout = this->getMaterialInterface()->descriptorSetLayout();

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the material descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		/* Prepare the descriptor set layout for bindless textures. */
		if ( setIndexes.isSetEnabled(SetType::PerBindless) )
		{
			auto descriptorSetLayout = renderer.bindlessTextureManager().descriptorSetLayout();

			if ( descriptorSetLayout == nullptr )
			{
				Tracer::error(ClassId, "Unable to get the bindless textures descriptor set layout !");

				return false;
			}

			descriptorSetLayouts.emplace_back(descriptorSetLayout);
		}

		Abstract::generatePushConstantRanges(this->shaderProgram()->vertexShader()->pushConstantBlockDeclarations(), pushConstantRanges, VK_SHADER_STAGE_VERTEX_BIT);

		return true;
	}

	bool
	SceneRendering::generateVertexShader (Program & program) noexcept
	{
		/* Create the vertex shader. */
		const bool isCubemapTarget = this->renderTarget()->isCubemap();

		auto * vertexShader = program.initVertexShader(
			this->name( ) + "VertexShader",
			this->isFlagEnabled(IsInstancingEnabled),
			this->isAdvancedRendering(),
			this->isFlagEnabled(IsRenderableFacingCamera),
			isCubemapTarget,
			this->isMultiDrawIndirectEnabled()
		);
		vertexShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		/* NOTE: Cubemap rendering requires multiview extension for gl_ViewIndex. */
		if ( isCubemapTarget )
		{
			vertexShader->setExtensionBehavior("GL_EXT_multiview", "enable");
		}

		if ( !this->declareMatrixPushConstantBlock(*vertexShader) )
		{
			return false;
		}

		/* Declare the view uniform block. */
		if ( !this->declareViewUniformBlock(*vertexShader) )
		{
			return false;
		}

		/* NOTE: The position is always required and available. */
		if ( !vertexShader->requestSynthesizeInstruction(ShaderVariable::PositionScreenSpace) )
		{
			return false;
		}

		/* If present, generate the material shader code. */
		if ( this->materialEnabled() && !this->getMaterialInterface()->generateVertexShaderCode(*this, *vertexShader) )
		{
			TraceError{ClassId} << "Unable to generate vertex shader code part for material '" << this->getMaterialInterface()->name() << "' !";

			return false;
		}

		/* Generate the lighting shader code. */
		if ( m_scene->lightSet().isEnabled() && this->isFlagEnabled(IsLightingEnabled) )
		{
			if ( !m_lightGenerator.generateVertexShaderCode(*this, *vertexShader) )
			{
				Tracer::error(ClassId, "Unable to generate vertex shader code part for lighting !");

				return false;
			}

			/* Ensure svNormalViewSpace is available as a fragment shader input for the MRT normal output.
			 * Only needed when the render target has a normals attachment (color attachment count >= 2),
			 * i.e. the internal scene render target.  The swap chain has only 1 color attachment. */
			if ( m_hasNormalsAttachment )
			{
				if ( !vertexShader->requestSynthesizeInstruction(ShaderVariable::NormalViewSpace, Saphir::VariableScope::ToNextStage) )
				{
					return false;
				}
			}
		}

		return vertexShader->generateSourceCode(*this);
	}

	bool
	SceneRendering::generateFragmentShader (Program & program) noexcept
	{
		/* Create the fragment shader. */
		auto * fragmentShader = program.initFragmentShader(this->name( ) + "FragmentShader");
		fragmentShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		/* Automatic input declarations from vertex shader. */
		if ( !fragmentShader->connectFromPreviousShader(*program.vertexShader()) )
		{
			return false;
		}

		/* Common part of fragment shader. */
		fragmentShader->declareDefaultOutputFragment();

		/* Declare the MRT normals output only when the render target has a normals attachment. */
		if ( m_hasNormalsAttachment )
		{
			fragmentShader->declare(Declaration::OutputFragment{1, Keys::GLSL::FloatVector4, Keys::ShaderVariable::OutputNormal});
		}

		/* Declare the MRT material properties output only when the render target has the attachment. */
		if ( m_hasMaterialPropertiesAttachment )
		{
			fragmentShader->declare(Declaration::OutputFragment{2, Keys::GLSL::FloatVector4, Keys::ShaderVariable::OutputMaterialProperties});
		}

		/* If a material is present, generate the shader code (optional). */
		if ( this->materialEnabled() && !this->getMaterialInterface()->generateFragmentShaderCode(*this, m_lightGenerator, *fragmentShader) )
		{
			TraceError{ClassId} << "Unable to generate fragment shader code part for material '" << this->getMaterialInterface()->name() << "' !";

			return false;
		}

		/* If the light is enabled, generate the shader code (optional). */
		if ( m_scene->lightSet().isEnabled() && this->isFlagEnabled(IsLightingEnabled) )
		{
			/* Declare the view uniform block. */
			if ( !m_scene->lightSet().isUsingStaticLighting() && !this->declareViewUniformBlock(*fragmentShader) )
			{
				return false;
			}

			if ( !m_lightGenerator.generateFragmentShaderCode(*this, *fragmentShader) )
			{
				Tracer::error(ClassId, "Unable to generate fragment shader code part for lighting !");

				return false;
			}
		}

		/* Generates the fragment output. */
		if ( m_scene->lightSet().isEnabled() && this->isFlagEnabled(IsLightingEnabled) )
		{
			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = " << m_lightGenerator.fragmentColor() << ';';

			if ( m_hasNormalsAttachment )
			{
				/* Write view-space normal to MRT attachment 1 for post-process effects (SSAO, SSR, RTR, RTAO).
				 * Uses the final normal (perturbed by normal mapping when active) instead of the geometric normal.
				 * Alpha packs roughness + metalness: alpha = roughness + metalness * 2.0.
				 * Decode: metalness = (alpha >= 2.0) ? 1.0 : 0.0; roughness = alpha - metalness * 2.0;
				 * Only the ambient/simple pass writes the actual normal. Light passes use additive
				 * blending, so they must output zero to preserve the existing normal value. */
				if ( m_renderPassType == RenderPassType::AmbientPass || m_renderPassType == RenderPassType::SimplePass )
				{
					const auto normalExpr = m_lightGenerator.finalNormalViewSpaceExpression();
					const auto roughnessExpr = m_lightGenerator.roughnessShaderExpression();
					const auto metalnessExpr = m_lightGenerator.metalnessShaderExpression();
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(" << normalExpr << ", " << roughnessExpr << " + " << metalnessExpr << " * 2.0);";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(0.0);";
				}
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				/* Write material properties to MRT attachment 2 for post-process effect modulation.
				 * Nibble-packed RGBA: R[hi:lo]=reflection:reserved, G[hi:lo]=aoResponse:shadowResponse,
				 * B[hi:lo]=bloomContrib:emissiveMask, A[hi:lo]=fogResponse:dofMask.
				 * Values derived from declared surface properties (metalness, roughness, AO, emissive).
				 * Light passes output zero (additive blending preserves the existing values). */
				if ( m_renderPassType == RenderPassType::AmbientPass || m_renderPassType == RenderPassType::SimplePass )
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = " << m_lightGenerator.materialPropertiesExpression() << ";";
				}
				else
				{
					Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = vec4(0.0);";
				}
			}
		}
		else if ( this->materialEnabled() )
		{
			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = " << this->getMaterialInterface()->fragmentColor() << ';';

			if ( m_hasNormalsAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(0.0, 0.0, 1.0, 0.5);";
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = vec4(0.0, 1.0, 240.0 / 255.0, 1.0);";
			}
		}
		else
		{
			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = vec4(1.0, 0.0, 1.0, 1.0);";

			if ( m_hasNormalsAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputNormal << " = vec4(0.0, 0.0, 1.0, 0.5);";
			}

			if ( m_hasMaterialPropertiesAttachment )
			{
				Code{*fragmentShader, Location::Output} << ShaderVariable::OutputMaterialProperties << " = vec4(0.0, 1.0, 240.0 / 255.0, 1.0);";
			}
		}

		/* Discard nearly transparent pixels to avoid blending artifacts. */
		if ( this->materialEnabled() && this->getMaterialInterface()->blendingMode() != BlendingMode::None )
		{
			Code{*fragmentShader, Location::Output} << "if ( " << ShaderVariable::OutputFragment << ".a < 0.01 ) discard;";
		}

		return fragmentShader->generateSourceCode(*this);
	}
	
	bool
	SceneRendering::onGraphicsPipelineConfiguration (const Program & /*program*/, GraphicsPipeline & graphicsPipeline) noexcept
	{
		const auto * renderableInstance = this->getRenderableInstance();
		const auto * renderable = renderableInstance->renderable();

		/* NOTE: Use dynamic viewport and scissor to avoid pipeline recreation on window resize. */
		{
			const StaticVector< VkDynamicState, 16 > dynamicStates{
				VK_DYNAMIC_STATE_VIEWPORT,
				VK_DYNAMIC_STATE_SCISSOR
			};

			if ( !graphicsPipeline.configureDynamicStates(dynamicStates) )
			{
				Tracer::error(ClassId, "Unable to configure the graphics pipeline dynamic states !");

				return false;
			}
		}

		if ( !graphicsPipeline.configureRasterizationState(m_renderPassType, renderable->layerRasterizationOptions(this->layerIndex())) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline rasterization state !");

			return false;
		}

		if ( !graphicsPipeline.configureDepthStencilState(m_renderPassType, *renderableInstance) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline depth/stencil state !");

			return false;
		}

		if ( !graphicsPipeline.configureColorBlendState(m_renderPassType, *renderable->material(this->layerIndex())) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline color blend state !");

			return false;
		}

		/* When the render target has MRT attachments, duplicate the color blend attachment
		 * for each additional buffer. This ensures:
		 * - AmbientPass (no blend): writes the actual values (replace).
		 * - Light passes (additive): writes vec4(0.0), adding nothing to the existing values. */
		if ( m_hasNormalsAttachment )
		{
			graphicsPipeline.appendColorBlendAttachment(graphicsPipeline.colorBlendAttachments()[0]);
		}

		if ( m_hasMaterialPropertiesAttachment )
		{
			graphicsPipeline.appendColorBlendAttachment(graphicsPipeline.colorBlendAttachments()[0]);
		}

		return true;
	}

	size_t
	SceneRendering::computeProgramCacheKey () const noexcept
	{
		/* NOTE: Helper function to combine hash values (boost::hash_combine style). */
		const auto hashCombine = [] (size_t & seed, size_t value) noexcept {
			seed ^= value + 0x9e3779b9 + (seed << 6) + (seed >> 2);
		};

		size_t hash = 0;

		/* 1. Render pass handle (critical for pipeline compatibility). */
		if ( const auto * framebuffer = this->renderTarget()->framebuffer(); framebuffer != nullptr )
		{
			hashCombine(hash, reinterpret_cast< size_t >(framebuffer->renderPass()->handle()));
		}

		/* 2. Render target type (cubemap vs single layer). */
		hashCombine(hash, static_cast< size_t >(this->renderTarget()->isCubemap()));

		/* 3. Renderable identity (geometry + material combination via resource name). */
		if ( this->isRenderableInstanceAvailable() )
		{
			const auto * renderable = this->getRenderable();

			if ( renderable != nullptr )
			{
				hashCombine(hash, Hash::FNV1a(renderable->name()));
			}
		}

		/* 4. Layer index. */
		hashCombine(hash, static_cast< size_t >(this->layerIndex()));

		/* 5. Render pass type. */
		hashCombine(hash, static_cast< size_t >(m_renderPassType));

		/* 6. Generator flags (instancing, lighting, facing camera, etc.). */
		hashCombine(hash, static_cast< size_t >(this->flags()));

		/* 7. Scene static lighting state (affects shader generation). */
		if ( m_scene != nullptr && m_scene->lightSet().isUsingStaticLighting() )
		{
			hashCombine(hash, 1ULL);
		}

		/* 8. Material layout signature to separate incompatible pipelines (e.g. Standard Refl/Refract). */
		if ( this->materialEnabled() )
		{
			if ( const auto & layout = this->getMaterialInterface()->descriptorSetLayout(); layout != nullptr )
			{
				hashCombine(hash, layout->getHash());
			}
		}

		return hash;
	}
}
