/*
 * src/Saphir/Generator/ShadowCasting.cpp
 * This file is part of Emeraude-Engine
 *
 * Copyright (C) 2010-2026 - Sébastien Léon Claude Christian Bémelmans "LondNoir" <londnoir@gmail.com>
 *
 * Emeraude-Engine is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Emeraude-Engine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Emeraude-Engine; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Complete project and additional information can be found at :
 * https://github.com/londnoir/emeraude-engine
 *
 * --- THIS IS AUTOMATICALLY GENERATED, DO NOT CHANGE ---
 */

#include "ShadowCasting.hpp"

/* Local inclusions. */
#include "Graphics/RenderTarget/Abstract.hpp"
#include "Libs/Hash/FNV1a.hpp"
#include "Libs/SourceCodeParser.hpp"
#include "Saphir/Code.hpp"

namespace EmEn::Saphir::Generator
{
	using namespace Libs;
	using namespace Graphics;
	using namespace Vulkan;
	using namespace Saphir::Keys;

	void
	ShadowCasting::prepareUniformSets (SetIndexes & setIndexes) noexcept
	{
		if ( this->isFlagEnabled(IsInstancingEnabled) )
		{
			setIndexes.enableSet(SetType::PerView);
		}
	}

	bool
	ShadowCasting::onGenerateShadersCode (Program & program) noexcept
	{
		/* Generate the vertex shader stage. */
		if ( !this->generateVertexShader(program) )
		{
			/* NOTE: Error message is generated by the function. */
			return false;
		}

		if ( this->debuggingEnabled() )
		{
			program.vertexShader()->traceSuccessfulGeneration();
		}

		/* Generate the geometry shader stage. */
		if ( this->renderTarget()->isCubemap() )
		{
			if ( !this->generateGeometryShader(program) )
			{
				/* NOTE: Error message is generated by the function. */
				return false;
			}

			if ( this->debuggingEnabled() )
			{
				program.geometryShader()->traceSuccessfulGeneration();
			}
		}

		return true;
	}

	bool
	ShadowCasting::onCreateDataLayouts (Renderer & /*renderer*/, const SetIndexes & /*setIndexes*/, StaticVector< std::shared_ptr< DescriptorSetLayout >, 4 > & /*descriptorSetLayouts*/, StaticVector< VkPushConstantRange, 4 > & pushConstantRanges) noexcept
	{
		Abstract::generatePushConstantRanges(this->shaderProgram()->vertexShader()->pushConstantBlockDeclarations(), pushConstantRanges, VK_SHADER_STAGE_VERTEX_BIT);

		return true;
	}

	bool
	ShadowCasting::generateVertexShader (Program & program) noexcept
	{
		auto * vertexShader = program.initVertexShader(
			this->name( ) + "VertexShader",
			this->isFlagEnabled(IsInstancingEnabled),
			false,
			this->isFlagEnabled(IsRenderableFacingCamera)
		);
		vertexShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		if ( !this->declareMatrixPushConstantBlock(*vertexShader) )
		{
			return false;
		}

		if ( this->renderTarget()->isCubemap() )
		{
			vertexShader->requestSynthesizeInstruction(ShaderVariable::GLPositionWorldSpace);
		}
		else
		{
			vertexShader->requestSynthesizeInstruction(ShaderVariable::PositionScreenSpace);
		}

		return vertexShader->generateSourceCode(*this);
	}

	bool
	ShadowCasting::generateGeometryShader (Program & program) noexcept
	{
		auto * geometryShader = program.initGeometryShader(
			this->name( ) + "GeometryShader",
			Declaration::InputPrimitive{Declaration::InputPrimitiveType::Triangles},
			Declaration::OutputPrimitive{Declaration::OutputPrimitiveType::TriangleStrip, 18}
		);
		geometryShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		if ( !this->declareMatrixPushConstantBlock(*geometryShader) )
		{
			return false;
		}

		/* Declare the view uniform block. */
		if ( !this->declareViewUniformBlock(*geometryShader) )
		{
			return false;
		}

		geometryShader->declare(Declaration::StageOutput{this->getNextShaderVariableLocation(), GLSL::FloatVector4, ShaderVariable::FragCoord, GLSL::Smooth});

		Code{*geometryShader} <<
			"for ( int faceIndex = 0; faceIndex < 6; ++faceIndex )" << Line::End <<
			"{" << Line::End <<
			"	gl_Layer = faceIndex;" << Line::Blank <<

			"	for ( int i = 0; i < gl_in.length(); ++i )" << Line::End <<
			"	{" << Line::End <<
			"		" << ShaderVariable::FragCoord << " = gl_in[i].gl_Position;" << Line::End <<
			"		gl_Position = " << CubeViewUB(UniformBlock::Component::Instance, "faceIndex", UniformBlock::Component::ViewProjectionMatrix) << " * " << ShaderVariable::FragCoord << ";" << Line::End <<
			"		EmitVertex();" << Line::End <<
			"	}" << Line::Blank <<

			"	EndPrimitive();" << Line::End <<
			"}";

		return geometryShader->generateSourceCode(*this);
	}

	bool
	ShadowCasting::generateFragmentShader (Program & program) noexcept
	{
		auto * fragmentShader = program.initFragmentShader(this->name( ) + "FragmentShaderDEBUG");
		fragmentShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		if ( this->renderTarget()->isCubemap() )
		{
			const auto position = CubeViewUB(UniformBlock::Component::Instance, "0", UniformBlock::Component::PositionWorldSpace);
			const auto viewProperties = CubeViewUB(UniformBlock::Component::Instance, "0", UniformBlock::Component::ViewProperties);

			/* Declare the view uniform block. */
			if ( !this->declareViewUniformBlock(*fragmentShader) )
			{
				return false;
			}

			if ( !fragmentShader->connectFromPreviousShader(*program.geometryShader()) )
			{
				return false;
			}

			Code{*fragmentShader} << "const float distance = distance(" << ShaderVariable::FragCoord << ", " << position << ") / " << viewProperties << ".w;";

			fragmentShader->declareDefaultOutputFragment();

			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = vec4(distance, distance, distance, 1.0);";
		}
		else
		{
			fragmentShader->declareDefaultOutputFragment();

			Code{*fragmentShader, Location::Output} << ShaderVariable::OutputFragment << " = vec4(gl_FragCoord.z, gl_FragCoord.z, gl_FragCoord.z, 1.0);";
		}

		return fragmentShader->generateSourceCode(*this);
	}

	bool
	ShadowCasting::onGraphicsPipelineConfiguration (const Program & /*program*/, GraphicsPipeline & graphicsPipeline) noexcept
	{
		if ( !graphicsPipeline.configureRasterizationState(RenderPassType::SimplePass) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline rasterization state !");

			return false;
		}

		/* Configure the rasterizer */
		{
			VkPipelineRasterizationStateCreateInfo createInfo{};
			createInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
			createInfo.pNext = nullptr;
			createInfo.flags = 0;
			createInfo.depthClampEnable = VK_FALSE;
			createInfo.rasterizerDiscardEnable = VK_FALSE;
			createInfo.polygonMode = VK_POLYGON_MODE_FILL;
			createInfo.cullMode = VK_CULL_MODE_NONE;
			createInfo.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
			createInfo.depthBiasEnable = VK_TRUE;
			createInfo.depthBiasConstantFactor = 1.25F;
			createInfo.depthBiasClamp = 0.0F;
			createInfo.depthBiasSlopeFactor = 1.75F;
			createInfo.lineWidth = 1.0F;

			if ( !graphicsPipeline.configureRasterizationState(createInfo) )
			{
				Tracer::error(ClassId, "Unable to configure the graphics pipeline rasterization state !");

				return false;
			}
		}

		/* Configure the depth/stencil buffer */
		{
			VkPipelineDepthStencilStateCreateInfo createInfo{};
			createInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
			createInfo.pNext = nullptr;
			createInfo.flags = 0;
			createInfo.depthTestEnable = VK_TRUE;
			createInfo.depthWriteEnable = VK_TRUE;
			createInfo.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;
			createInfo.depthBoundsTestEnable = VK_FALSE;
			createInfo.stencilTestEnable = VK_FALSE;
			createInfo.minDepthBounds = 0.0F;
			createInfo.maxDepthBounds = 0.0F;

			if ( !graphicsPipeline.configureDepthStencilState(createInfo) )
			{
				Tracer::error(ClassId, "Unable to configure the graphics pipeline depth/stencil state !");

				return false;
			}
		}

		/* NOTE: Use dynamic viewport and scissor to avoid pipeline recreation on window resize. */
		const StaticVector< VkDynamicState, 16 > dynamicStates{
			VK_DYNAMIC_STATE_VIEWPORT,
			VK_DYNAMIC_STATE_SCISSOR
		};

		if ( !graphicsPipeline.configureDynamicStates(dynamicStates) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline dynamic states !");

			return false;
		}

		return true;
	}

	size_t
	ShadowCasting::computeProgramCacheKey () const noexcept
	{
		/* NOTE: Helper function to combine hash values (boost::hash_combine style). */
		const auto hashCombine = [] (size_t & seed, size_t value) noexcept {
			seed ^= value + 0x9e3779b9 + (seed << 6) + (seed >> 2);
		};

		size_t hash = Hash::FNV1a(ClassId);

		/* 1. Render target type (cubemap vs single layer). */
		hashCombine(hash, static_cast< size_t >(this->renderTarget()->isCubemap()));

		/* 2. Renderable identity (geometry combination via resource name). */
		if ( this->isRenderableInstanceAvailable() )
		{
			const auto * renderable = this->getRenderable();

			if ( renderable != nullptr )
			{
				hashCombine(hash, Hash::FNV1a(renderable->name()));
			}
		}

		/* 3. Layer index. */
		hashCombine(hash, static_cast< size_t >(this->layerIndex()));

		/* 4. Generator flags (instancing, facing camera). */
		hashCombine(hash, static_cast< size_t >(this->flags()));

		return hash;
	}
}
