/*
 * src/Saphir/Generator/ShadowCasting.cpp
 * This file is part of Emeraude-Engine
 *
 * Copyright (C) 2010-2026 - Sébastien Léon Claude Christian Bémelmans "LondNoir" <londnoir@gmail.com>
 *
 * Emeraude-Engine is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Emeraude-Engine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Emeraude-Engine; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Complete project and additional information can be found at :
 * https://github.com/londnoir/emeraude-engine
 *
 * --- THIS IS AUTOMATICALLY GENERATED, DO NOT CHANGE ---
 */

#include "ShadowCasting.hpp"

/* Local inclusions. */
#include "Graphics/RenderTarget/Abstract.hpp"
#include "Libs/Hash/FNV1a.hpp"
#include "Vulkan/Framebuffer.hpp"
#include "Vulkan/RenderPass.hpp"
#include "Libs/SourceCodeParser.hpp"
#include "Saphir/Code.hpp"

namespace EmEn::Saphir::Generator
{
	using namespace Libs;
	using namespace Graphics;
	using namespace Vulkan;
	using namespace Saphir::Keys;

	void
	ShadowCasting::prepareUniformSets (SetIndexes & setIndexes) noexcept
	{
		/* NOTE: Enable PerView set for instancing OR multiview rendering (cubemap or CSM).
		 * Cubemap shadow maps require the UBO with 6 view matrices indexed by gl_ViewIndex.
		 * CSM shadow maps require the UBO with N (up to 4) cascade view matrices indexed by gl_ViewIndex. */
		if ( this->isFlagEnabled(IsInstancingEnabled) || this->renderTarget()->isCubemap() || this->renderTarget()->isCascadedShadowMap() )
		{
			setIndexes.enableSet(SetType::PerView);
		}
	}

	bool
	ShadowCasting::onGenerateShadersCode (Program & program) noexcept
	{
		/* Generate the vertex shader stage.
		 * NOTE: For cubemap shadow maps, multiview rendering is used instead of geometry shaders.
		 * The vertex shader uses gl_ViewIndex to select the correct view matrix from the UBO. */
		if ( !this->generateVertexShader(program) )
		{
			/* NOTE: Error message is generated by the function. */
			return false;
		}

		/* Generate the fragment shader stage.
		 * NOTE: Only for cubemap shadow maps to write linear depth. */
		if ( this->renderTarget()->isCubemap() )
		{
			if ( !this->generateFragmentShader(program) )
			{
				/* NOTE: Error message is generated by the function. */
				return false;
			}
		}

		if ( this->debuggingEnabled() )
		{
			program.vertexShader()->traceSuccessfulGeneration();

			if ( this->renderTarget()->isCubemap() )
			{
				program.fragmentShader()->traceSuccessfulGeneration();
			}
		}

		return true;
	}

	bool
	ShadowCasting::onCreateDataLayouts (Renderer & /*renderer*/, const SetIndexes & /*setIndexes*/, StaticVector< std::shared_ptr< DescriptorSetLayout >, 4 > & /*descriptorSetLayouts*/, StaticVector< VkPushConstantRange, 4 > & pushConstantRanges) noexcept
	{
		Abstract::generatePushConstantRanges(this->shaderProgram()->vertexShader()->pushConstantBlockDeclarations(), pushConstantRanges, VK_SHADER_STAGE_VERTEX_BIT);

		if ( this->renderTarget()->isCubemap() )
		{
			Abstract::generatePushConstantRanges(this->shaderProgram()->fragmentShader()->pushConstantBlockDeclarations(), pushConstantRanges, VK_SHADER_STAGE_FRAGMENT_BIT);
		}

		return true;
	}

	bool
	ShadowCasting::generateFragmentShader (Program & program) noexcept
	{
		auto * fragmentShader = program.initFragmentShader(this->name() + "FragmentShader");
		fragmentShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		/* Input: Position in view space (from Vertex Shader). */
		if ( !fragmentShader->connectFromPreviousShader(*program.vertexShader()) )
		{
			return false;
		}

		/* Uniform: View Matrices to get the far plane distance. */
		if ( !this->declareViewUniformBlock(*fragmentShader) )
		{
			return false;
		}

		/* Main: Write linear depth to gl_FragDepth. */
		Code{*fragmentShader} << "float linearDepth = length(" << ShaderVariable::PositionViewSpace << ".xyz);";
		
		/* NOTE: layout(std140, set = X, binding = Y) uniform View { ... float farDistance; ... } ubView; */
		/* The far distance is at offset 27 (floats) in the UBO buffer data array. */
		Code{*fragmentShader} << "linearDepth /= " << UniformBlock::View << "." << UniformBlock::Component::ViewProperties << ".w;";
		Code{*fragmentShader} << "gl_FragDepth = linearDepth;";

		return fragmentShader->generateSourceCode(*this);
	}

	bool
	ShadowCasting::generateVertexShader (Program & program) noexcept
	{
		const bool isCubemap = this->renderTarget()->isCubemap();
		const bool isCSM = this->renderTarget()->isCascadedShadowMap();
		const bool useMultiview = isCubemap || isCSM;

		/* NOTE: For cubemap/CSM shadow maps, enable multiview mode which uses gl_ViewIndex.
		 * The vertex shader will use gl_ViewIndex to select the correct view matrix from the UBO.
		 * For cubemaps: 6 view matrices for 6 cube faces.
		 * For CSM: N view matrices for N cascades (different UBO layout). */
		auto * vertexShader = program.initVertexShader(
			this->name() + "VertexShader",
			this->isFlagEnabled(IsInstancingEnabled),
			false,
			this->isFlagEnabled(IsRenderableFacingCamera),
			isCubemap /* enableCubemapMode - only for cubemap, NOT for CSM */
		);
		vertexShader->setExtensionBehavior("GL_ARB_separate_shader_objects", "enable");

		/* Enable CSM mode for cascaded shadow maps (different UBO layout than cubemap). */
		if ( isCSM )
		{
			vertexShader->enableCSMMode();
		}

		/* NOTE: Enable multiview extension for cubemap/CSM rendering to use gl_ViewIndex. */
		if ( useMultiview )
		{
			vertexShader->setExtensionBehavior("GL_EXT_multiview", "enable");
		}

		if ( !this->declareMatrixPushConstantBlock(*vertexShader) )
		{
			return false;
		}

		/* For multiview (cubemap/CSM), declare the view UBO with view matrices. */
		if ( useMultiview )
		{
			if ( !this->declareViewUniformBlock(*vertexShader) )
			{
				return false;
			}
		}

		/* Request the screen space position output.
		 * In multiview mode, this will use the UBO view matrix indexed by gl_ViewIndex. */
		if ( !vertexShader->requestSynthesizeInstruction(ShaderVariable::PositionScreenSpace) )
		{
			return false;
		}

		/* For cubemap shadow maps, we need the view space position in the fragment shader to compute linear depth.
		 * NOTE: CSM does not need linear depth - it uses standard depth values. */
		if ( isCubemap )
		{
			if ( !vertexShader->requestSynthesizeInstruction(ShaderVariable::PositionViewSpace) )
			{
				return false;
			}
		}

		return vertexShader->generateSourceCode(*this);
	}

	bool
	ShadowCasting::onGraphicsPipelineConfiguration (const Program & /*program*/, GraphicsPipeline & graphicsPipeline) noexcept
	{
		if ( !graphicsPipeline.configureRasterizationState(RenderPassType::SimplePass) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline rasterization state !");

			return false;
		}

		/* Configure the rasterizer */
		{
			VkPipelineRasterizationStateCreateInfo createInfo{};
			createInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
			createInfo.pNext = nullptr;
			createInfo.flags = 0;
			createInfo.depthClampEnable = VK_FALSE;
			createInfo.rasterizerDiscardEnable = VK_FALSE;
			createInfo.polygonMode = VK_POLYGON_MODE_FILL;
			createInfo.cullMode = VK_CULL_MODE_NONE;
			createInfo.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
			createInfo.depthBiasEnable = VK_TRUE;
			createInfo.depthBiasConstantFactor = 1.25F;
			createInfo.depthBiasClamp = 0.0F;
			createInfo.depthBiasSlopeFactor = 1.75F;
			createInfo.lineWidth = 1.0F;

			if ( !graphicsPipeline.configureRasterizationState(createInfo) )
			{
				Tracer::error(ClassId, "Unable to configure the graphics pipeline rasterization state !");

				return false;
			}
		}

		/* Configure the depth/stencil buffer */
		{
			VkPipelineDepthStencilStateCreateInfo createInfo{};
			createInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
			createInfo.pNext = nullptr;
			createInfo.flags = 0;
			createInfo.depthTestEnable = VK_TRUE;
			createInfo.depthWriteEnable = VK_TRUE;
			createInfo.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;
			createInfo.depthBoundsTestEnable = VK_FALSE;
			createInfo.stencilTestEnable = VK_FALSE;
			createInfo.minDepthBounds = 0.0F;
			createInfo.maxDepthBounds = 0.0F;

			if ( !graphicsPipeline.configureDepthStencilState(createInfo) )
			{
				Tracer::error(ClassId, "Unable to configure the graphics pipeline depth/stencil state !");

				return false;
			}
		}

		/* NOTE: Use dynamic viewport and scissor to avoid pipeline recreation on window resize. */
		const StaticVector< VkDynamicState, 16 > dynamicStates{
			VK_DYNAMIC_STATE_VIEWPORT,
			VK_DYNAMIC_STATE_SCISSOR
		};

		if ( !graphicsPipeline.configureDynamicStates(dynamicStates) )
		{
			Tracer::error(ClassId, "Unable to configure the graphics pipeline dynamic states !");

			return false;
		}

		return true;
	}

	size_t
	ShadowCasting::computeProgramCacheKey () const noexcept
	{
		/* NOTE: Helper function to combine hash values (boost::hash_combine style). */
		const auto hashCombine = [] (size_t & seed, size_t value) noexcept {
			seed ^= value + 0x9e3779b9 + (seed << 6) + (seed >> 2);
		};

		size_t hash = Hash::FNV1a(ClassId);

		/* 1. Render pass handle (critical for pipeline compatibility). */
		if ( const auto * framebuffer = this->renderTarget()->framebuffer(); framebuffer != nullptr )
		{
			hashCombine(hash, reinterpret_cast< size_t >(framebuffer->renderPass()->handle()));
		}

		/* 2. Render target type (cubemap vs single layer vs CSM). */
		hashCombine(hash, static_cast< size_t >(this->renderTarget()->isCubemap()));
		hashCombine(hash, static_cast< size_t >(this->renderTarget()->isCascadedShadowMap()));

		/* 3. Renderable identity (geometry combination via resource name). */
		if ( this->isRenderableInstanceAvailable() )
		{
			const auto * renderable = this->getRenderable();

			if ( renderable != nullptr )
			{
				hashCombine(hash, Hash::FNV1a(renderable->name()));
			}
		}

		/* 4. Layer index. */
		hashCombine(hash, static_cast< size_t >(this->layerIndex()));

		/* 5. Generator flags (instancing, facing camera). */
		hashCombine(hash, static_cast< size_t >(this->flags()));

		return hash;
	}
}
