/*
 * src/Saphir/ShaderManager.hpp
 * This file is part of Emeraude-Engine
 *
 * Copyright (C) 2010-2026 - Sébastien Léon Claude Christian Bémelmans "LondNoir" <londnoir@gmail.com>
 *
 * Emeraude-Engine is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Emeraude-Engine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Emeraude-Engine; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Complete project and additional information can be found at :
 * https://github.com/EmeraudeEngine/emeraude-engine
 *
 * --- THIS IS AUTOMATICALLY GENERATED, DO NOT CHANGE ---
 */

#pragma once

/* STL inclusions. */
#include <array>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <map>
#include <memory>
#include <string>
#include <vector>

/* Third-party inclusions. */
#include <vulkan/vulkan.h>

/* Local inclusions for inheritances. */
#include "ServiceInterface.hpp"
#include "ObservableTrait.hpp"

/* Local inclusions for usages. */
#include "StaticVector.hpp"
#include "Types.hpp"
#include "Vulkan/Types.hpp"

/* Forward declarations. */
namespace EmEn
{
	namespace Vulkan
	{
		class Device;
		class ShaderModule;
	}

	namespace Saphir
	{
		class AbstractShader;
		class Program;
	}

	class PrimaryServices;
}

namespace EmEn::Saphir
{
	/**
	 * @brief All recognized shader source file extensions.
	 * @note Used to filter shader source files apart from any other file sharing the
	 * same cache directory (readCache(), clearCache()).
	 */
	static constexpr std::array< const char * const, 6 > ShaderFileExtensions{
		VertexShaderFileExtension,
		TesselationControlShaderFileExtension,
		TesselationEvaluationShaderFileExtension,
		GeometryShaderFileExtension,
		FragmentShaderFileExtension,
		ComputeShaderFileExtension
	};

	/**
	 * @brief The shader manager service class.
	 * @note [OBS][STATIC-OBSERVABLE]
	 * @extends EmEn::ServiceInterface This is a service.
	 * @extends EmEn::Base::ObservableTrait This service is observable.
	 */
	class ShaderManager final : public ServiceInterface, public Base::ObservableTrait
	{
		public:

			/** @brief Class identifier. */
			static constexpr auto ClassId{"ShaderManagerService"};

			/**
			 * @brief Observable notification codes.
			 * @note ShaderCompilationSucceed carries the shader identifier (std::string) as its
			 * notify() payload. ShaderCompilationFailed carries a
			 * std::pair< std::string, std::string > of (shader identifier, source code annotated
			 * with the compiler errors inline).
			 */
			enum NotificationCode : std::uint8_t
			{
				ShaderCompilationSucceed, ///< A shader was successfully compiled to SPIR-V.
				ShaderCompilationFailed, ///< A shader failed to compile; see the class note for the payload.
				/* Enumeration boundary. */
				MaxEnum
			};

			/**
			 * @brief Constructs the shader manager.
			 * @note Defined out-of-line (not inline here): it initializes a
			 * std::unique_ptr< GLSLangContext > pointing to an incomplete type, whose
			 * complete definition is only visible in ShaderManager.cpp.
			 * @param primaryServices A reference to the primary services.
			 */
			explicit ShaderManager (PrimaryServices & primaryServices) noexcept;

			/**
			 * @brief Destructs the shader manager.
			 * @note Defined out-of-line for the same reason as the constructor: destroying
			 * the std::unique_ptr< GLSLangContext > requires the complete type for the
			 * deleter. See docs/windows-export-api.md § "exported pimpl".
			 */
			~ShaderManager () override;

			/**
			 * @brief Returns the unique identifier for this class [Thread-safe].
			 * @return size_t
			 */
			static
			size_t
			getClassUID () noexcept
			{
				return Base::Hash::FNV1a(ClassId);
			}

			/** @copydoc EmEn::Base::ObservableTrait::classUID() const */
			[[nodiscard]]
			size_t
			classUID () const noexcept override
			{
				return getClassUID();
			}

			/** @copydoc EmEn::Base::ObservableTrait::is() const */
			[[nodiscard]]
			bool
			is (size_t classUID) const noexcept override
			{
				return classUID == getClassUID();
			}

			/**
			 * @brief Returns whether the print of shader source code in the console is enabled.
			 * @return bool
			 */
			[[nodiscard]]
			bool
			showSourceCode () const noexcept
			{
				return m_showSourceCode;
			}

			/**
			 * @brief Builds a Vulkan shader module from a shader generated by the Saphir system.
			 * @note The shader must have already been generated (AbstractShader::isGenerated())
			 * before calling this. Its hash (AbstractShader::hash()) keys both the in-memory
			 * module cache and the disk source/binary caches, so a shader whose generated source
			 * is unchanged is served from cache instead of being recompiled.
			 * @param device A reference to a device smart pointer.
			 * @param shader A reference to a Saphir shader.
			 * @return std::shared_ptr< Vulkan::ShaderModule >, or nullptr on failure (service not
			 * usable, shader not generated, compilation failed, or Vulkan module creation failed).
			 */
			[[nodiscard]]
			std::shared_ptr< Vulkan::ShaderModule > getShaderModuleFromGeneratedShader (const std::shared_ptr< Vulkan::Device > & device, const AbstractShader & shader) noexcept;

			/**
			 * @brief Builds a Vulkan shader module from source code.
			 * @todo This entry point bypasses the disk cache entirely (no lookup, no write):
			 * unlike getShaderModuleFromGeneratedShader(), every call recompiles from scratch.
			 * @param device A reference to a device smart pointer.
			 * @param shaderName A reference to a string.
			 * @param shaderType The type of shader.
			 * @param sourceCode A reference to a string.
			 * @return std::shared_ptr< Vulkan::ShaderModule >, or nullptr on failure.
			 */
			[[nodiscard]]
			std::shared_ptr< Vulkan::ShaderModule > getShaderModuleFromSourceCode (const std::shared_ptr< Vulkan::Device > & device, const std::string & shaderName, ShaderType shaderType, const std::string & sourceCode) noexcept;

			/**
			 * @brief Returns shader modules corresponding to a program.
			 * @note If the program declares specialization constants, the fragment shader
			 * module's boolean constants are set from Program::fragmentSpecializationConstantsBool()
			 * and its pipeline shader stage create info is rebuilt before being returned (used for
			 * features toggled at pipeline level, e.g. shadow mapping).
			 * @param device A reference to a device smart pointer.
			 * @param program A reference to a program smart pointer.
			 * @return Base::StaticVector< std::shared_ptr< Vulkan::ShaderModule >, 5 >, empty if
			 * any of the program's shaders failed to produce a module.
			 */
			[[nodiscard]]
			Base::StaticVector< std::shared_ptr< Vulkan::ShaderModule >, 5 > getShaderModules (const std::shared_ptr< Vulkan::Device > & device, const std::shared_ptr< Program > & program) noexcept;

		private:

			/** @copydoc EmEn::ServiceInterface::onInitialize() */
			bool onInitialize () noexcept override;

			/** @copydoc EmEn::ServiceInterface::onTerminate() */
			bool onTerminate () noexcept override;

			/**
			 * @brief Compiles a shader from a saphir generated source code.
			 * @param shader A reference to a shader smart pointer.
			 * @param binaryCode A reference to the binary data vector to complete.
			 * @return bool
			 */
			[[nodiscard]]
			bool compile (const AbstractShader & shader, std::vector< uint32_t > & binaryCode) noexcept;

			/**
			 * @brief Compiles a shader from a source code.
			 * @param shaderName A reference to a string.
			 * @param type The shader type.
			 * @param sourceCode A reference to a string.
			 * @param binaryCode A reference to the binary data vector to complete.
			 * @return bool
			 */
			[[nodiscard]]
			bool compile (const std::string & shaderName, ShaderType type, const std::string & sourceCode, std::vector< uint32_t > & binaryCode) noexcept;

			/**
			 * @brief Writes a shader source code on disk cache.
			 * @param shader A reference to a shader.
			 * @return bool
			 */
			[[nodiscard]]
			bool cacheShaderSourceCode (const AbstractShader & shader) const noexcept;

			/**
			 * @brief Writes a shader binary on disk cache.
			 * @param shader A reference to a shader.
			 * @param binaryCode A reference to the binary data vector.
			 * @return bool
			 */
			[[nodiscard]]
			bool cacheShaderBinary (const AbstractShader & shader, const std::vector< uint32_t > & binaryCode) const noexcept;

			/**
			 * @brief Reads the cache to get shader source codes and binaries.
			 * @return void
			 */
			void readCache () noexcept;

			/**
			 * @brief Removes all sources and binary from shader cache.
			 * @return void
			 */
			void clearCache () noexcept;

			/**
			 * @brief Generates a unique cache filepath for the shader source.
			 * @param shader A reference to a shader.
			 * @return std::filesystem::path
			 */
			[[nodiscard]]
			std::filesystem::path generateShaderSourceCacheFilepath (const AbstractShader & shader) const noexcept;

			/**
			 * @brief Generates a unique cache filepath for the shader binary.
			 * @param shader A reference to a shader.
			 * @return std::filesystem::path
			 */
			[[nodiscard]]
			std::filesystem::path generateShaderBinaryCacheFilepath (const AbstractShader & shader) const noexcept;

			/**
			 * @brief Returns the shader hash from the filepath.
			 * @note Expects a filename matching "<name>_<hash>.<extension>" exactly (one '_',
			 * and after it exactly one '.'). Returns 0 — never a valid hash — otherwise; callers
			 * (readCache()) must treat 0 as "reject this cache entry", not as an actual hash.
			 * @param filepath A reference to a filesystem path.
			 * @return size_t
			 */
			[[nodiscard]]
			static size_t extractHashFromFilepath (const std::filesystem::path & filepath) noexcept;

			/**
			 * @brief Checks whether a binary exists in the cache.
			 * @note Returns false whenever the binary disk cache is disabled, even if a matching
			 * entry exists — callers must not read false as "not compiled yet".
			 * @param shader A reference to a shader.
			 * @param binaryCode A reference to the binary code to complete if exists in the cache.
			 * @return bool
			 */
			[[nodiscard]]
			bool checkBinaryFromCache (const AbstractShader & shader, std::vector< uint32_t > & binaryCode) noexcept;

			/**
			 * @brief Prints compilation errors.
			 * @note Beyond tracing the annotated source, this also fires the
			 * ShaderCompilationFailed notification with a std::pair< std::string, std::string >
			 * of (shaderIdentifier, annotated source code) as its payload.
			 * @param shaderIdentifier A reference to a string.
			 * @param sourceCode A reference to a string.
			 * @param log A pointer to a C-string.
			 * @return void
			 */
			void printCompilationErrors (const std::string & shaderIdentifier, const std::string & sourceCode, const char * log) noexcept;

			/**
			 * @brief Converts a shader type from saphir to Vulkan type.
			 * @param shaderType The Saphir shader type.
			 * @return VkShaderStageFlagBits, or 0 (no bit set) if shaderType is not one of the
			 * known Saphir shader types.
			 */
			[[nodiscard]]
			static VkShaderStageFlagBits vkShaderType (ShaderType shaderType) noexcept;

			/** @brief Name of the cache subdirectory holding cached GLSL source files. */
			static constexpr auto ShaderSourcesDirectoryName{"shader-sources"};
			/** @brief Name of the cache subdirectory holding compiled SPIR-V binaries. */
			static constexpr auto ShaderBinariesDirectoryName{"shader-binaries"};

			/**
			 * @brief The GLSLang compilation context: built-in resource limits, shader
			 * includer, GLSL profile, target version and message filter.
			 * @note Held by pointer so that <glslang/Public/ShaderLang.h> stays OUT of this
			 * header. Every one of these fields is a glslang type (TBuiltInResource,
			 * DirStackFileIncluder, EProfile, EShMessages), so keeping them by value leaked
			 * the whole glslang public header into each of the 21 translation units
			 * including ShaderManager.hpp — and, through Graphics/Renderer.hpp, into 81 more.
			 * Defined in ShaderManager.cpp; never null after a successful onInitialize().
			 */
			struct GLSLangContext;

			PrimaryServices & m_primaryServices;
			std::map< size_t, std::shared_ptr< Vulkan::ShaderModule > > m_shaderModules; ///< Loaded shader modules, keyed by AbstractShader::hash().
			std::map< size_t, std::filesystem::path > m_cachedShaderSourceCodes; ///< Disk source cache index, keyed by shader hash. Populated by readCache() but only consulted by clearCache(): cacheShaderSourceCode() always (re)writes, it never looks up this index first.
			std::map< size_t, std::filesystem::path > m_cachedShaderBinaries; ///< Disk binary cache index, keyed by shader hash; looked up by checkBinaryFromCache() to skip a recompilation.
			std::filesystem::path m_shadersSourcesDirectory;
			std::filesystem::path m_shadersBinariesDirectory;
			std::unique_ptr< GLSLangContext > m_glslang;
			bool m_showInformation{false};
			bool m_showSourceCode{false};
			bool m_sourceCodeCacheEnabled{false};
			bool m_binaryCacheEnabled{false};
	};
}
