#!/bin/bash

set -e

echo "Installing build dependencies ..."

sudo apt update
sudo apt install g++ cmake ninja-build nasm python3 libvulkan-dev vulkan-tools vulkan-validationlayers vulkan-validationlayers-dev xorg-dev libxkbcommon-dev

echo "Done !"
